services:
  - type: web
    name: bar-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y fonts-dejavu-core
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
